---
# proxmox
base_path: '/root'

vm_templates:
  - image_name: 'noble-server-cloudimg-amd64.img'
    image_url: 'https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img'
    vm_id: 100
    vm_name: 'ubuntu-noble-cloudinit-template'
    vm_memory: 2048
    vm_cores: 2
    vm_bridge: 'vmbr1'
    vm_storage: 'local-lvm'
