#!/usr/bin/env ansible-playbook
---

- name: Prepare Proxmox
  hosts: all
  become: true
  gather_facts: true

  tasks:


    - name: Logical volume management
      ansible.builtin.include_role:
        name: lvm
      tags:
        - lvm

    - name: Initialize Proxmox
      ansible.builtin.include_role:
        name: proxmox_init
      tags:
        - init

    - name: Create Proxmox VM template
      ansible.builtin.include_role:
        name: proxmox_templates
      tags:
        - template
